#!/bin/bash
sudo emerge -q app-arch/lz4 schedtool
cd /usr/share/orchid/tools/kernel
sudo sed "/_configfile=/c\_configfile=\"running-kernel\"" /usr/share/orchid/tools/kernel/customization.cfg > tmp.cfg
sudo cp tmp.cfg /usr/share/orchid/tools/kernel/customization.cfg
sudo rm -f tmp.cfg
sudo ./update-kernel-versions.sh
sudo ./install.sh install
