#!/bin/bash
echo "Activation des noyaux latest."
sudo echo sys-kernel/gentoo-kernel-bin ~amd64 >> /etc/portage/package.accept_keywords/zz-autounmask
sudo echo virtual/dist-kernel ~amd64 >> /etc/portage/package.accept_keywords/zz-autounmask
sudo orchid-update
