#!/bin/bash
mkdir -p /usr/share/orchid/tools/kernel
git clone https://github.com/Frogging-Family/linux-tkg /usr/share/orchid/tools/kernel
cd /usr/share/orchid/tools/kernel
sudo ./update-kernel-versions.sh
