#!/bin/bash
echo "Basculement sur la sync via rsync ..."
echo "Nettoyage de l'ancienne structure ..."
sudo rm -f /etc/portage/repos.conf/gentoo.conf
sudo rm -rf /var/db/repos/gentoo
cd /etc/portage/repos.conf
echo "Mise en place de la nouvelle méthode ..."
sudo wget https://raw.githubusercontent.com/wamuu-sudo/orchid/main/swapper/classic-conf/gentoo.conf
echo "Syncronisation des dépots, cette opération peut prendre plusieurs minutes ..."
sudo emerge --sync
echo "Syncronisation des métadatas, la durée varie en fonction de votre matériel ..."
sudo egencache --update --repo gentoo --jobs=4
sudo eix-sync
echo "Basculement sur rsync terminé. Pour revenir à la méthode Git, utilisez la commande orchid-swap-git."
