#!/bin/bash
echo "Activation des pilotes Nvidia latest ..."
sudo echo media-video/ffmpeg nvenc >> /etc/portage/package.use/nvenc
sudo echo x11-drivers/nvidia-drivers ~amd64 >> /etc/portage/package.accept_keywords/zz-autounmask
sudo echo media-video/nvidia-video-codec ~amd64 >> /etc/portage/package.accept_keywords/zz-autounmask
sudo euse -E nvenc
sudo emerge -avuN nvidia-drivers nvidia-video-codec nvidia-video-codec ffmpeg dev-util/nvidia-cuda-toolkit 
sudo orchid-update
