#!/bin/bash
echo ""
echo "Syncro des métadatas, de la liste des paquets disponibles, et vérification de la présence de mises à jour ..."
echo ""
echo "Attention, si un changement des USE_FLAGS est requis, la commande dispatch-conf est nécessaire pour prendre en compte le changement !"
echo ""
sudo orchid-sync && sudo eix-sync -q && sudo emerge -qavuDN @world && emerge @module-rebuild && flatpak update && emerge --depclean -q && snapper -c root create && orchid-boot-update
