#!/bin/bash
mkdir -p /usr/share/orchid/tools/kernel
echo "Vérification de la présence du repo TkG ..."
git clone https://github.com/Frogging-Family/linux-tkg /usr/share/orchid/tools/kernel &> /dev/null
cd /usr/share/orchid/tools/kernel
sudo ./update-kernel-versions.sh
