#!/bin/bash
sudo emerge -qav --autounmask-write --autounmask=y $@ && sudo snapper -c config create && sudo orchid-boot-update
echo "Attention, si vous installez un paquet masqué, il faut utiliser la commande dispatch-conf afin de prendre en compte les nouveaux USE."
echo "Il faut relancer la commande orchid-install par la suite."
